# Generated by Django 5.2.3 on 2025-06-24 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcript_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterStrength',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GraduateAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='attributestrengthmap',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='participation',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.AddField(
            model_name='attributestrengthmap',
            name='value',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attributestrengthmap',
            name='weight',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='participation',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcript_app.event'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcript_app.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='attributestrengthmap',
            name='strength',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcript_app.characterstrength'),
        ),
        migrations.AlterField(
            model_name='attributestrengthmap',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcript_app.graduateattribute'),
        ),
        migrations.AlterField(
            model_name='event',
            name='attributes',
            field=models.ManyToManyField(to='transcript_app.graduateattribute'),
        ),
        migrations.RemoveField(
            model_name='attributestrengthmap',
            name='event',
        ),
        migrations.RemoveField(
            model_name='participation',
            name='achievement',
        ),
        migrations.RemoveField(
            model_name='participation',
            name='role',
        ),
        migrations.DeleteModel(
            name='Strength',
        ),
        migrations.DeleteModel(
            name='Attribute',
        ),
    ]
