# Generated by Django 5.2.3 on 2025-06-24 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcript_app', '0002_characterstrength_graduateattribute_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attributestrengthmap',
            old_name='strength',
            new_name='character_strength',
        ),
        migrations.RenameField(
            model_name='attributestrengthmap',
            old_name='attribute',
            new_name='graduate_attribute',
        ),
        migrations.RemoveField(
            model_name='attributestrengthmap',
            name='value',
        ),
    ]
